### ISSUE TITLE
abrir shell

### ISSUE THREAD

**Issue by danielagadens** [ocefpaf/pyrantine#1]
Para abrir o shell eu devo ir na pasta que eu instalei o miniconda e clicar no "conda", certo?
quando eu faço isso ele abre um prompt mas ele se fecha quase que imediatamente.
![image](https://user-images.githubusercontent.com/48091015/77937709-1a91ba00-728b-11ea-895f-b3618c867560.png)

**Comment by ocefpaf** [comment]
> Para abrir o shell eu devo ir na pasta que eu instalei o miniconda e clicar no "conda", certo?

@danielagadens checa se o `miniconda` criou o atalho para o shell dele como na [figura do item `g)` das instruções do Windows](https://github.com/ocefpaf/pyrantine/blob/master/step-by-step-windows.md#g-procure-o-%C3%ADcone-anaconda-prompt-miniconda3-e-clique-nele-para-certificar-que-a-instala%C3%A7%C3%A3o-correu-corretamente).

**Comment by danielagadens** [comment]
beleza! dessa forma deu certo!
está terminando de baixar.
mas eu instalei todas as coisas no meu usuário porque não consegui colocar em pastas....
tem como modificar o diretorio depois?

**Comment by danielagadens** [comment]
está terminando de baixar os pacotes do passo [6/](https://github.com/ocefpaf/pyrantine/)

**Comment by ocefpaf** [comment]
> mas eu instalei todas as coisas no meu usuário porque não consegui colocar em pastas....
> tem como modificar o diretorio depois?

Você se refere a instalação do `miniconda` ou ao clone das aulas? Se for o primeiro não se preocupe, deixa assim mesmo. Se for o último tem como mudar sim.

**Comment by danielagadens** [comment]
estou agora no último passo! seria o caso de desativar o meu antivirus? porque acredito que tudo deu certo, mas agora uma janela do meu navegador deveria abrir, certo?
![image](https://user-images.githubusercontent.com/48091015/78041922-bbde4600-7347-11ea-983f-f7901694e4a9.png)

**Comment by danielagadens** [comment]
agora aparentemente ele me deu um link de um token para eu colar no meu browser. mas nao estou conseguindo copiar ele....
![image](https://user-images.githubusercontent.com/48091015/78042181-0fe92a80-7348-11ea-8956-c4201fcd9ac4.png)

**Comment by ocefpaf** [comment]
> estou agora no último passo! seria o caso de desativar o meu antivirus? porque acredito que tudo deu certo, mas agora uma janela do meu navegador deveria abrir, certo?

Parece tudo certo mesmo! Só o jupyter-notebook que não abriu. Deveria abrir automaticamente mesmo. Não creio ser o anti-virus mas nunca se sabe :-/

> agora aparentemente ele me deu um link de um token para eu colar no meu browser. mas nao estou conseguindo copiar ele....

O que acontece quando passa o mouse lá? Não seleciona? Vou pegar um Windows aqui e testar. Já volto aqui e reporto o que consegui (ou não).

**Comment by danielagadens** [comment]
consegui abrir o link mas ele fica nisso: 
![image](https://user-images.githubusercontent.com/48091015/78050976-6b6ce580-7353-11ea-8921-28a5a5fd4324.png)

**Comment by ocefpaf** [comment]
> consegui abrir o link mas ele fica nisso:

Isso pode ser alguma firewall. Só para ter certeza, clicou no que começar com "http://localhost..."?

Você tem o chrome ou firefox?

**Comment by danielagadens** [comment]
tentei todos... uso o firefox

**Comment by ocefpaf** [comment]
> tentei todos... uso o firefox

Quer tentar por ligação via zoom? Assim você pode compartilhar a tela e fica um pouco mais fácil ver o que tá rolando.

Se quiser me passa o melhor horário pra você que eu crio o link do zoom.

**Comment by danielagadens** [comment]
Pode ser!!! Depois das 15 já estou disponíve!

**Comment by ocefpaf** [comment]
Vou colocar o link para o zoom. No Grupo, até mais tarde!

**Comment by danielagadens** [comment]
bom dia!!
tentei instalar mais uma vez hoje de manhã
e apareceu isso
![image](https://user-images.githubusercontent.com/48091015/78249412-afcbc300-74c4-11ea-9535-b6b9f126b551.png)
e o bynder funcionou, então será que posso ir para o bynder?

**Comment by ocefpaf** [comment]
@danielagadens isso é com o avast "desligado," certo? Se for parece que os mecanismos de segurança do Windows bloquearam completamente o python do miniconda :-(

É Windows 7 ou 10?

**Comment by danielagadens** [comment]
isso! é windows 10

**Comment by ocefpaf** [comment]
@danielagadens as vezes uma versão antiga do miniconda funciona melhor. Tenta refazer a instalação com essa aqui:

https://repo.continuum.io/miniconda/Miniconda3-4.6.14-Windows-x86_64.exe

Caso não funcione podemos tentar usar o Windows Linux Subsystem do Windows 10 (https://docs.microsoft.com/en-us/windows/wsl/install-win10), mas vamos tentar evitar isso por enquanto para não complexar demais.

**Comment by danielagadens** [comment]
beleza estou baixando a outra versão

**Comment by danielagadens** [comment]
estou no passo 2 e deu esse erro

![image](https://user-images.githubusercontent.com/48091015/79129972-8e988b80-7d7c-11ea-94c1-39d3ce792f6b.png)

**Comment by ocefpaf** [comment]
> estou no passo 2 e deu esse erro

O diretório já existe. Pode apagar ele e executar o comando novamente. No terminal, na mesma past onde você está, execute:

```
rmdir /S pyrantine
```

e depois continue com o git clone...

**Comment by danielagadens** [comment]
beleza, funcionou, estou no passo 6

**Comment by danielagadens** [comment]
![image](https://user-images.githubusercontent.com/48091015/79174187-4c009e80-7dd0-11ea-9182-53a459a28d4e.png)

**Comment by ocefpaf** [comment]
@danielagadens o Windows é terrível em remover arquivos. Quando você tentou criar o ambiente novo ele te disse que já existia e por isso não criou. Vamos tentar remover o diretório do ambiante "na marra."

Se você navegar pelo explorer mesmo e for para `C:\Users\Daniela Gadens\Miniconda3\envs` você vai ver o diretório `PYCOURSE`. Apaga ele e tenta do passo `5` pra frente.

**Comment by danielagadens** [comment]
![image](https://user-images.githubusercontent.com/48091015/79354272-90945300-7f12-11ea-89e7-6c41a2f09c07.png)

**Comment by ocefpaf** [comment]
@danielagadens vamos marcar uma sessão de zoom? Acho que só com share screen mesmo pra gente "debugar" esses problemas.

**Comment by danielagadens** [comment]
podemos marcar sim!
estou disponivel!

**Comment by ocefpaf** [comment]
> podemos marcar sim!
> estou disponivel!

Hoje às 15:00 ou amanhã às 13:00 serve para você?

**Comment by danielagadens** [comment]
pode ser hoje as 13!!

**Comment by ocefpaf** [comment]
> pode ser hoje as 13!!

Blz. Te mando o para a reunião link pelo WhatsApp.

**Comment by ocefpaf** [comment]
Fechando esse aqui pq a intalação da Dani está funcionando.
