### ISSUE TITLE
Exercício Boias PIRATA

### ISSUE THREAD

**Issue by micabroggio** [ocefpaf/pyrantine#11]
Olá Filipe, segue o notebook e o link dos dados da boia

https://gist.github.com/micabroggio/20e70638cc4d565faf144af3055b83f8

http://goosbrasil.org:8080/pirata/B0n35w.nc.html

**Comment by ocefpaf** [comment]
O problema não é nos dados como eu achava, mas sim no fato de estar fazendo o ajuste no agrupando por "month." O que acontece é que o seu index tem a frequência "M" de meses. Na minha opinião o que está acontecendo é um bug no matplotlib pq ele deveria aceitar esse index mesmo assim.

Um truque é converte tudo para pandas e plotar com o método do pandas. Na célula [36], como o `trend` já é uma série do mandas você pode mudar

```python
ax0.plot(month_mean.index, trend, label="trend")
```

para 

```python
trend.plot(ax=ax0, label="trend")
```

Na célula [42] adiciona uma linha logo após a criação do `fitted` para transformar em série do pandas:

```python
fitted = pd.Series(
    index=interped_signal_cutted.index,
    data=fitted
)
```

e depois mude

```python
ax0.plot(
    interped_signal_cutted.index,
    fitted,
    label="ajuste"
)
```
para

```python
fitted.plot(ax=ax0, label="ajuste")
```
