### ISSUE TITLE
erro com o git pull 

### ISSUE THREAD

**Issue by camilakneubl** [ocefpaf/pyrantine#14]
Minha atualização com o git pull não está funcionando e aparece um erro:
![image](https://user-images.githubusercontent.com/48098060/83914986-bf77ba00-a748-11ea-8c8c-eafe59b91677.png)

**Comment by ocefpaf** [comment]
Aha! Conflitos existem pq você modificou um arquivo pre-existente. Pode remover todo o diretório sem medo e clonar ele novamente com:

```
git clone https://github.com/ocefpaf/pyrantine.git
```

As modificações que você fez estão de certa forma guardadas nas gists dos exercícios.

**Comment by camilakneubl** [comment]
Entendi!! obrigada

**Comment by ocefpaf** [comment]
Fecha o "issue" aqui se funcionou. Mas se ainda está com problemas escreve aqui...
