### ISSUE TITLE
dados CTD

### ISSUE THREAD

**Issue by Bru-od** [ocefpaf/pyrantine#15]
Oi Filipe,
os dados do exercicio da aula de CTD apresenta valores que sabemos que é um erro do inicio da amostragem - profundidade zero (segue a figura)

![Captura de tela de 2020-06-15 11-09-01](https://user-images.githubusercontent.com/63169741/84667658-090a9680-aef9-11ea-9d94-05e7023636fa.png)

Gostaria de me informar sobre qual a melhor maneira de resolver isso. Seria colocando nan? Criar um intervalo pra identificar onde ocorre esses valores?

**Comment by ocefpaf** [comment]
O primeiro passo é checar o instrumento secundário. Caso o problema não exista nele, ou seja menor, podemos usar ele. Se estiver em ambos pode não ser problema do aparelho em si, mas do lançamento do cast. Daí tem que colocar NaNs no problema e seguir pra frente.

Checa as células 21-23 desse notebook: https://nbviewer.jupyter.org/gist/ocefpaf/8645f977208efd16f8c7ecaf038cf7e0
