### ISSUE TITLE
lp_filter

### ISSUE THREAD

**Issue by Bru-od** [ocefpaf/pyrantine#16]
quando faço o lp_filter ele fica igual filtrado e não filtrado

![Captura de tela de 2020-06-17 10-00-40](https://user-images.githubusercontent.com/63169741/84901292-a5f83b80-b081-11ea-91c2-c309f3967cab.png)

**Comment by ocefpaf** [comment]
Igual nesse "zoom" da figura. O *jitter* é de baixa frequência e para visualiza você terá que dar um zoom num pedacinho da linha. No meu exemplo tem um zoom lá, mas como os dados mudaram você terá que acertar um novo intervalo.

Checa a linha `ax.axis([xmin, xmax, ymin, ymax])` e ache os seus valores de xmin, xmax, ymin, ymax.

**Comment by Bru-od** [comment]
Eu fiz isso mas continua dando a mesma coisa, não importa onde eu delimite ax.axis

![Captura de tela de 2020-06-17 12-54-47](https://user-images.githubusercontent.com/63169741/84920761-fbd8dd80-b099-11ea-9f83-2d72ba238883.png)

Inclusive também tentei o intervalo que você colocou no seu exemplo e não deu certo
