### ISSUE TITLE
Problemas com o git pull 

### ISSUE THREAD

**Issue by camilakneubl** [ocefpaf/pyrantine#17]
![image](https://user-images.githubusercontent.com/48098060/85870387-51507100-b7a3-11ea-841a-49c718ad8b17.png)

Não entendi porque aconteceu isso. 

Preciso recriar o ambiente?

**Comment by ocefpaf** [comment]
> Não entendi porque aconteceu isso.

Isso significa que arquivos modificados no repositório também foram modificados localmente. Logo, um conflito ao tentar pegar os arquivos novos.

> Preciso recriar o ambiente?

Não precisa. Você pode apagar o diretório `pyrantine` localmente e fazer um "clone" novo.
