### ISSUE TITLE
Exercício 00: recriar o ambiente e atualizar o repositório

### ISSUE THREAD

**Issue by ocefpaf** [ocefpaf/pyrantine#2]
```
conda deactivate
conda env remove --name PYCOURSE

cd pyrantine
git pull  # se isso falhar apague o diretório e refaça o clone.

conda env create --file environment.yml --name PYCOURSE
```

- [x] Juliana (@juoceano)
- [ ] Michelle (@MiPieroni)
- [x] Daniela (@danielagadens)
- [x] Camila (@camilakneubl)
- [x] Micael (@micabroggio)
- [x] Bruna (@Bru-od)
- [ ] Lisiane (@lisiheinzen)

**Comment by camilakneubl** [comment]
![image](https://user-images.githubusercontent.com/48098060/78712035-59102000-78ee-11ea-9fc8-eb25416ecd00.png)

Estou com esse problema.

**Comment by ocefpaf** [comment]
@camilakneubl falha minha. Nós instalamos o `git` no ambiente `base`! Não tem `git` mesmo no **PYCOURSE** (separação de contexto, lembra ;-p).

Você tem duas soluções:

1. instalar co git no ambiente **PYCOURSE** com `conda install git`
2. sair do ambiente **PYCOURSE** com `conda deactivate`, executar o `git pull`, e terminar o exercício daí.

Eu recomendo a `2` pq parte do exercício é destruir e re-criar o ambiente de aula.

**Comment by camilakneubl** [comment]
![image](https://user-images.githubusercontent.com/48098060/79171973-c8dc4a00-7dc9-11ea-98ec-522094556ae3.png)

Não sei o que eu fiz, mas ao tentar recriar o ambiente não consigo acessar o jupyter

**Comment by ocefpaf** [comment]
Acho que você terá que fazer o mesmo que a Dani aqui:

https://github.com/ocefpaf/pyrantine/issues/1#issuecomment-613515056

Ah Windows...

**Comment by danielagadens** [comment]
![image](https://user-images.githubusercontent.com/48091015/80221633-f58b2f80-861b-11ea-988b-230806cbc7f9.png)
estou com o mesmo problema...

**Comment by ocefpaf** [comment]
Fechando esse aqui pq acho que só a Lisi ainda está com problemas de instalação e vamos tentar arrumar amanhã.
