### ISSUE TITLE
Exercício 01: comentar o live-coding-plotagem.ipynb

### ISSUE THREAD

**Issue by ocefpaf** [ocefpaf/pyrantine#3]
Pessoal, façam novamente o `git pull` para pode pegar as últimas atualizações, chequem se tem o notebook `notebooks/00-basic-plotting/live-coding-plotagem.ipynb` lá, e façam os exercícios listado nele.

- [ ] Michelle (@MiPieroni)
- [x] [Daniela (@danielagadens)](https://gist.github.com/ocefpaf/5104d5dd8d03aae28431ca48464615b5)
- [X] [Camila (@camilakneubl)](http://nbviewer.ipython.org/5edbbe896bdd9b1054a61e6201eb2a04)
- [X] [Micael (@micabroggio)](https://nbviewer.jupyter.org/gist/micabroggio/5aec57bef6261644db6222bbb6022d2e)
- [X] [Bruna (@Bru-od)](https://nbviewer.jupyter.org/urls/gist.githubusercontent.com/Bru-od/333a2115a7425e7be9d70a8de7c17291/raw/1e9d936c299eca28c37ea40ae512a9abcee0325c/gistfile1.txt)
- [x] [Lisiane (@lisiheinzen)](https://nbviewer.jupyter.org/gist/ocefpaf/d63dd9f69107df594e6346ed3ba26a2d)

**Comment by juoceano** [comment]
Depois de fazer os exercícios listados, devo renomear o notebook e enviá-lo para o github?

**Comment by ocefpaf** [comment]
> Depois de fazer os exercícios listados, devo renomear o notebook e enviá-lo para o github?

Não precisa renomear e vou mostrar como "mandar" ele na próxima aula. Por agora é só comentar mesmo.

O notebook com os melhores comentários vai ganhar um livro de Python!

**Comment by Bru-od** [comment]
Então é só clicar em save and checkpoint?

**Comment by ocefpaf** [comment]
> Então é só clicar em save and checkpoint?

Ao modificar localmente sim. É só salvar, que deve acontecer automaticamente ou você pode apertar ctrl+s, ou pelo menu como você fez.

**Comment by danielagadens** [comment]
Filipe, eu fiz dessa forma mas hoje fui ver que meus arquivos não salvaram... ou não estão aparecendo pra mim...

**Comment by ocefpaf** [comment]
> Filipe, eu fiz dessa forma mas hoje fui ver que meus arquivos não salvaram... ou não estão aparecendo pra mim...

Vamos tentar achar hoje na ligação. Senão o cachorro virtual comeu seu dever de casa, sem problema ;-p

**Comment by danielagadens** [comment]
hahhaha eu salvei de qualquer forma em um bloco de notas na verdade, dai posso upar ele aqui também ou te enviar

**Comment by ocefpaf** [comment]
Show! Ta valendo.

**Comment by danielagadens** [comment]
[live-coding-plotagem.txt](https://github.com/ocefpaf/pyrantine/files/4512312/live-coding-plotagem.txt)

**Comment by ocefpaf** [comment]
Pessoal, façam como a @danielagadens e coloquem o link do dever de casa aqui.

**Comment by camilakneubl** [comment]
<script src="https://gist.github.com/camilakneubl/5edbbe896bdd9b1054a61e6201eb2a04.js"></script>

**Comment by Bru-od** [comment]
<script src="https://gist.github.com/Bru-od/333a2115a7425e7be9d70a8de7c17291.js"></script>

**Comment by micabroggio** [comment]
https://gist.github.com/micabroggio/5aec57bef6261644db6222bbb6022d2e
*- -*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*Micael Fernando Broggio*

*Mestre em Oceanografia*
*Técnico em Agrimensura (CFT-BR 3954396580-3)Marinheiro Auxiliar de Convés
(CIR 441P2016000703)*
E-mail - micaoceano@gmail.com
E-mail - micaelfb@yahoo.com.br
Fone : (48) 996349033
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Em qua., 22 de abr. de 2020 às 18:28, Bru-od <notifications@github.com>
escreveu:

**Comment by danielagadens** [comment]
não sei se o link está funcionando >https://mybinder.org/v2/gh/ocefpaf/pyrantine/948e6857e2e695d57ea2e9883e3596f8cf03dbfd

**Comment by lisiheinzen** [comment]
https://mybinder.org/v2/gh/ocefpaf/pyrantine/948e6857e2e695d57ea2e9883e3596f8cf03dbfd 

Também não sei se o link vai funcionar, mas fiz o download do arquivo..

**Comment by lisiheinzen** [comment]
Filipe, tentei abrir o meu link e o da Dani e abre a página inicial do Binder sem aparecer nossos arquivos, acho que não fica salvo o upload do arquivo né?! Como podemos te enviar? Eu tenho ele salvo .py e .ypnb

**Comment by danielagadens** [comment]
Filipe, estava tentando fazer um mapa conforme esses exemplos
https://matplotlib.org/basemap/users/geography.html
com preenchimento e etc
porém ao copiar o seguinte código

****import matplotlib.pyplot as plt
from matplotlib.patches import Polygon
from mpl_toolkits.basemap import Basemap


def make_map():
    fig, ax = plt.subplots()
    m = Basemap(projection='merc', llcrnrlat=-35, 

urcrnrlat=7,
                llcrnrlon=-77, urcrnrlon=-32, 

resolution='i')
    m.ax = ax
    m.fillcontinents()
    return fig, m****

ele retornar com o seguinte erro:
como eu poderia solucioná-lo?


ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-28f4080bbcb6> in <module>
      1 import matplotlib.pyplot as plt
      2 from matplotlib.patches import Polygon
----> 3 from mpl_toolkits.basemap import Basemap
      4 
      5 

ModuleNotFoundError: No module named 'mpl_toolkits.basemap'

**Comment by ocefpaf** [comment]
> Filipe, tentei abrir o meu link e o da Dani e abre a página inicial do Binder sem aparecer nossos arquivos, acho que não fica salvo o upload do arquivo né?! Como podemos te enviar? Eu tenho ele salvo .py e .ypnb

Vamos resolver isso na ligação sobre a instalação @lisiheinzen. Já te envio mensagem para marcar.

**Comment by ocefpaf** [comment]
> Filipe, estava tentando fazer um mapa conforme esses exemplos
> [matplotlib.org/basemap/users/geography.html](https://matplotlib.org/basemap/users/geography.html)
> com preenchimento e etc
> porém ao copiar o seguinte código
> 
> ****import matplotlib.pyplot as plt
> from matplotlib.patches import Polygon
> from mpl_toolkits.basemap import Basemap
> 
> def make_map():
> fig, ax = plt.subplots()
> m = Basemap(projection='merc', llcrnrlat=-35,
> 
> urcrnrlat=7,
> llcrnrlon=-77, urcrnrlon=-32,
> 
> resolution='i')
> m.ax = ax
> m.fillcontinents()
> return fig, m****
> 
> ele retornar com o seguinte erro:
> como eu poderia solucioná-lo?
> 
> ModuleNotFoundError Traceback (most recent call last)
> in
> 1 import matplotlib.pyplot as plt
> 2 from matplotlib.patches import Polygon
> ----> 3 from mpl_toolkits.basemap import Basemap
> 4
> 5
> 
> ModuleNotFoundError: No module named 'mpl_toolkits.basemap'

Depois de ativar o ambiente digite:

```
conda install basemap
```

**Comment by micabroggio** [comment]
t = t / np.timedelta64(1, "D") / 365

O Felipe, você poderia mes esclarecer melhor o que essa linha faz?

**Comment by ocefpaf** [comment]
Pessoal, vou encerrar esse exercício e quero parabenizar todos pelos cometários bem feitos nos notebooks. Acima eu coloquei um link para as respostas de cada um e recomendo vocês a olharem as dos colegas para aprenderem uns com os outros.

Confesso que não foi fácil escolher o notebook "mais bem comentado." Mas... Quem ganhou o primeiro livro foi a @Bru-od. Quando acabar a quarentena eu te entrego o Whirlwind Tour Of Python, até lá todos podem dar uma olhada nele online: https://jakevdp.github.io/WhirlwindTourOfPython/

PS: tem mais livros para os próximos exercícios! Vamos manter uma competição saudável até o fim do curso.
