### ISSUE TITLE
 Explorando dados das Boias Piratas

### ISSUE THREAD

**Issue by camilakneubl** [ocefpaf/pyrantine#6]
A minha dúvida é referente ao inicio do exercício: como baixar e importar os dados da boia??

![image](https://user-images.githubusercontent.com/48098060/80721387-878bb000-8ad4-11ea-8611-e1d16a220bf5.png)

Não sei o que é OpenDAP mas lá tem uma opção pra Python

**Comment by ocefpaf** [comment]
Vamos ver OPeNDAP mais pra frente. Mas você deve ter a opção de baixar o CSV no botão azul, não?

**Comment by micabroggio** [comment]
t = t / np.timedelta64(1, "D") / 365

O Felipe, você poderia mes esclarecer melhor o que essa linha faz?

**Comment by ocefpaf** [comment]
> O Felipe, você poderia mes esclarecer melhor o que essa linha faz?
> t = t / np.timedelta64(1, "D") / 365

o mesmo
Pessoal (@juoceano, @MiPieroni, @danielagadens, @camilakneubl, @micabroggio, @Bru-od, @lisiheinzen) essa é uma pergunta importante pq essa parte código ficou obscuro no notebook. Aqui vai um passo-a-passo para explicar melhor.

1. Primeiramente a gente pegou somente os valores do index do tempo:

```python
t = interped_signal_cutted.index.values
t
array(['2005-08-24T12:00:00.000000000', '2005-08-25T12:00:00.000000000',
       '2005-08-26T12:00:00.000000000', ...,
       '2010-12-29T12:00:00.000000000', '2010-12-30T12:00:00.000000000',
       '2010-12-31T12:00:00.000000000'], dtype='datetime64[ns]')
```

2. Ao remover o primeiro valor de todo o vetor temos um vetor que começa do zero. Esse passo não é essencial mas ajuda a compreender o modelo sazonal.

```python
t = t - t[0]
t
array([                 0,     86400000000000,    172800000000000, ...,
       168739200000000000, 168825600000000000, 168912000000000000],
      dtype='timedelta64[ns]')
```

3. O primeiro valor é, como esperado, `0` e o segundo é `86400000000000`. Como o `dtype` diz que temos um `timedelta64[ns]'` )(nano-segundo), temos que converter isso para "dias por ano" para fazer nosso modelo sazonal. Isso pq a frequência dos dados é diária e o o ciclo sazonal corrector em 1-ano. Como fazer isso? Temos duas formas, uma é a "obscura" que usei acima, a função do `numpy.timedelta64` para mudar de nano-segundo para dia:

```python
one_day = np.timedelta64(1, "D")
t = t / one_day
t
array([0.000e+00, 1.000e+00, 2.000e+00, ..., 1.953e+03, 1.954e+03,
       1.955e+03])
```

4. Como podem ver agora temos dia 0, 1, 2, 3 ...
A outra forma de fazer seria dividir por 1e9*60*60*24, ou seja, nano-segundos, segundos, minutos, hora. Agora só falta dividir por 365 para termos dia-por-ano:

```python
t / 365
array([0.00000000e+00, 2.73972603e-03, 5.47945205e-03, ...,
       5.35068493e+00, 5.35342466e+00, 5.35616438e+00])
```

PS: a gente podia ter convertido para nano-segundo e ao invés de dividir por 365 dias ter divido por 365 em nanosegundos. Desde que as unidades sejam preservadas o nosso modelo resultaria na mesma curva.

**Comment by lisiheinzen** [comment]
Filipe, ao executar essa linha ta dando erro 

```python
%matplotlib inline
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(13, 5.5))
df.plot(ax=ax);

ValueError                                Traceback (most recent call last)
<ipython-input-25-bbed2e909928> in <module>
      4 
      5 fig, ax = plt.subplots(figsize=(13, 5.5))
----> 6 df.plot(ax=ax);

C:\Miniconda3\envs\PYCOURSE\lib\site-packages\pandas\plotting\_core.py in __call__(self, *args, **kwargs)
    845                     data.columns = label_name
    846 
--> 847         return plot_backend.plot(data, kind=kind, **kwargs)
    848 
    849     __call__.__doc__ = __doc__

C:\Miniconda3\envs\PYCOURSE\lib\site-packages\pandas\plotting\_matplotlib\__init__.py in plot(data, kind, **kwargs)
     59             kwargs["ax"] = getattr(ax, "left_ax", ax)
     60     plot_obj = PLOT_CLASSES[kind](data, **kwargs)
---> 61     plot_obj.generate()
     62     plot_obj.draw()
     63     return plot_obj.result

C:\Miniconda3\envs\PYCOURSE\lib\site-packages\pandas\plotting\_matplotlib\core.py in generate(self)
    259     def generate(self):
    260         self._args_adjust()
--> 261         self._compute_plot_data()
    262         self._setup_subplots()
    263         self._make_plot()

C:\Miniconda3\envs\PYCOURSE\lib\site-packages\pandas\plotting\_matplotlib\core.py in _compute_plot_data(self)
    414         numeric_data = numeric_data.copy()
    415         for col in numeric_data:
--> 416             numeric_data[col] = np.asarray(numeric_data[col])
    417 
    418         self.data = numeric_data

C:\Miniconda3\envs\PYCOURSE\lib\site-packages\pandas\core\frame.py in __setitem__(self, key, value)
   2936         else:
   2937             # set column
-> 2938             self._set_item(key, value)
   2939 
   2940     def _setitem_slice(self, key, value):

C:\Miniconda3\envs\PYCOURSE\lib\site-packages\pandas\core\frame.py in _set_item(self, key, value)
   2999         self._ensure_valid_index(value)
   3000         value = self._sanitize_column(key, value)
-> 3001         NDFrame._set_item(self, key, value)
   3002 
   3003         # check if we are modifying a copy

C:\Miniconda3\envs\PYCOURSE\lib\site-packages\pandas\core\generic.py in _set_item(self, key, value)
   3622 
   3623     def _set_item(self, key, value) -> None:
-> 3624         self._data.set(key, value)
   3625         self._clear_item_cache()
   3626 

C:\Miniconda3\envs\PYCOURSE\lib\site-packages\pandas\core\internals\managers.py in set(self, item, value)
   1084         unfit_val_locs = []
   1085         removed_blknos = []
-> 1086         for blkno, val_locs in libinternals.get_blkno_placements(blknos, group=True):
   1087             blk = self.blocks[blkno]
   1088             blk_locs = blklocs[val_locs.indexer]

pandas\_libs\internals.pyx in get_blkno_placements()

pandas\_libs\internals.pyx in pandas._libs.internals.get_blkno_indexers()

ValueError: Buffer has wrong number of dimensions (expected 1, got 0)
```

**Comment by ocefpaf** [comment]
Pode ser um problema na leitura dos dados. Lembra como fazer a `gist` do exercício anterior? Consegue fazer uma com o notebook e os dados? Se não lembrar podemos conectar amanhã e resolver isso.

PS: @camilakneubl não esqueci do seu problema! Podemos conectar no mesmo horário e resolver a sua instalação também. Que tal 13:00 nessa Sexta?

**Comment by lisiheinzen** [comment]
Confesso que não lembro.. 

Talvez eu esteja na estrada esse horário, mas assim que eu souber te confirmo!!

**Comment by camilakneubl** [comment]
Podemos sim!!

**Comment by danielagadens** [comment]
Filipe, sobre a importação de dados.
tentei importar diretamente do meu diretório

```python
import pandas as pd


df = pd.read_csv(r'C:\Users\Daniela Gadens\Downloads/dados_pirata.csv')
    index_col="datahora",
    parse_dates=True,
    usecols=range(1, 15),
)

df.head()
```

e ele retorna isso:

```
File "<ipython-input-2-460993357bc9>", line 5
    df = pd.read_csv
    ^
IndentationError: unexpected indent
```


o que pode estar acontecendo? tem alguma outra forma de fazer essa importação?

**Comment by ocefpaf** [comment]
@danielagadens deve ter um/ns espaços no início da linha do `df = pd.read_csv`, não?

PS: fica mais fácil para mim quando vocês abrem novos issues. Assim tem separação de contexto e eu não fico perdido nas mensagens ;-p

**Comment by ocefpaf** [comment]
@camilakneubl so para eu não me perder vamos fechar esse isso, pq o seu problema original foi resolvido, e vamos abrindo novos para os problemas que vão aparecendo.

PS: @lisiheinzen ainda estamos devendo uma checada no problema dos seus dados. Talvez a hoje na aula?

**Comment by lisiheinzen** [comment]
Pode ser! Quando for melhor pra ti!!
